server:
  servlet:
    context-path: /comanda-api
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cervejaria_gourmet_comanda_db?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
       hibernate:
          show-sql: true
          format_sql: true
          
cervejaria:
  api:
    produto:
      servers: http://localhost:8080 
